#! /usr/bin/env lua

-- Copyright (C) 2015,2017,2018 Tomoyuki Fujimori <moyu@dromozoa.com>
--
-- This file is part of dromozoa-ubench.
--
-- dromozoa-ubench is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- dromozoa-ubench is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with dromozoa-ubench.  If not, see <http://www.gnu.org/licenses/>.

local ubench = require "dromozoa.ubench"

local benchmarks = assert(assert(loadfile((...)))())

local context = ubench.context()
context:initialize()
-- estimate
-- run
context:terminate()
-- write

--[[
local format = string.format

local b = ubench()
b.benchmarks = assert(loadfile(arg[1]))()

local context = ubench.initialize()
local results = b:run()
context:terminate()
io.write(json.encode(results, { pretty = true }), "\n")
]]
