#! /usr/bin/env lua

-- Copyright (C) 2017 Tomoyuki Fujimori <moyu@dromozoa.com>
--
-- This file is part of dromozoa-ubench.
--
-- dromozoa-ubench is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- dromozoa-ubench is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with dromozoa-ubench.  If not, see <http://www.gnu.org/licenses/>.

local read_file = require "dromozoa.commons.read_file"
local uint32 = require "dromozoa.commons.uint32"
local json = require "dromozoa.commons.json"
local unix = require "dromozoa.unix"
local ubench = require "dromozoa.ubench"

for i = 1, #arg do
  local filename = arg[i]
  local dir = assert(filename:match("^(.+)%.json$"))
  local result, message, code = unix.mkdir(dir)
  if not result then
    if code == unix.EEXIST then
      if uint32.band(unix.stat(dir).st_mode, unix.S_IFMT) ~= unix.S_IFDIR then
        error(unix.strerror(unix.ENOTDIR))
      end
    else
      error(message)
    end
  end
  local dataset = ubench.report(json.decode(assert(read_file(filename))), dir)

  dataset:sort(function (a, b)
    return a.key < b.key
  end)

  local max = 0
  for data in dataset:each() do
    local n = #data.key
    if max < n then
      max = n
    end
  end
  local f = "%" .. max .. "s %9d\n"
  for data in dataset:each() do
    io.write(f:format(data.key, math.floor(data.avg + 0.5)))
  end
end
