#! /usr/bin/env lua

-- Copyright (C) 2018 Tomoyuki Fujimori <moyu@dromozoa.com>
--
-- This file is part of dromozoa-ubench.
--
-- dromozoa-ubench is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- dromozoa-ubench is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with dromozoa-ubench.  If not, see <http://www.gnu.org/licenses/>.

local unix = require "dromozoa.unix"

local scaling_governor_filename = "/sys/devices/system/cpu/cpufreq/policy0/scaling_governor"
local scaling_governor

local handle, message = io.open(scaling_governor_filename)
if handle then
  scaling_governor = handle:read "*l"
  handle:close()
  io.stderr:write("scaling_governor: ", scaling_governor, "\n")
else
  io.stderr:write(message, "\n")
end





